# Number of spaces per tab
tab_spaces = 2

# Use tabs instead of spaces.
# hard_tabs = true

# Maximum width of one line of code
max_width = 80

# Use field initialize shorthand if possible.
use_field_init_shorthand = true

# Replace uses of the try! macro by the ? shorthand
use_try_shorthand = true
