# this file again! g-e-o-m-e-t-r-i-c you should know the stuff
[package]
name = "guessing-game"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4" # random number generator
